In [ ]:
import pandas as pd

data = [['John', 50, 'Male', 'Austin', 70],
['Cataline', 45 ,'Female', 'San Francisco', 80],
['Matt', 30 ,'Male', 'Boston', 95],
['Oliver',35,'Male', 'New york', 65]]

# Column labels of the DataFrame
columns = ['Name','Age','Sex', 'City', 'Marks']

# Create a DataFrame df
df = pd.DataFrame(data, columns=columns)

# Sort values based on ‘Age’ column
df.sort_values(by=['Age'])

df.head()

       Name  Age     Sex           City  Marks
0      John   50    Male         Austin     70
1  Cataline   45  Female  San Francisco     80
2      Matt   30    Male         Boston     95
3    Oliver   35    Male       New york     65

In [ ]:
import pandas as pd

data = [['John', 50, 'Male', 'Austin', 70],
['Cataline', 45 ,'Female', 'San Francisco', 80],
['Matt', 30 ,'Male', 'Boston', 95],
['Oliver',35,'Male', 'New york', 65]]

# Column labels of the DataFrame
columns = ['Name','Age','Sex', 'City', 'Marks']

# Create a DataFrame df
df = pd.DataFrame(data, columns=columns)

# Sort values based on ‘Age’ column in ascending order and display
display(df.sort_values(by=['Age'], ascending=True))

       Name  Age     Sex           City  Marks
2      Matt   30    Male         Boston     95
3    Oliver   35    Male       New york     65
1  Cataline   45  Female  San Francisco     80
0      John   50    Male         Austin     70

In [ ]:
import pandas as pd

data = [['John', 50, 'Male', 'Austin', 70],
['Cataline', 45 ,'Female', 'San Francisco', 80],
['Matt', 30 ,'Male', 'Boston', 95],
['Oliver',35,'Male', 'New york', 65]]

# Column labels of the DataFrame
columns = ['Name','Age','Sex', 'City', 'Marks']

# Create a DataFrame df
df = pd.DataFrame(data, columns=columns)

# Sort values based on ‘Age’ column in ascending order and display
display(df.sort_values(by=['Age'], ascending=False))

       Name  Age     Sex           City  Marks
0      John   50    Male         Austin     70
1  Cataline   45  Female  San Francisco     80
3    Oliver   35    Male       New york     65
2      Matt   30    Male         Boston     95

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Cataline', 'Matt'],
        'Age': [50, 45, 30],
        'City': ['Austin', 'San Francisco', 'Boston'],
        'Marks' : [70, 80, 95]}

# Create a DataFrame df
df = pd.DataFrame(data)

new_df = df[(df.Name == "John") | (df.Marks > 90)]
print (new_df)

   Name  Age    City  Marks
0  John   50  Austin     70
2  Matt   30  Boston     95